#!/bin/bash

#SBATCH --partition=compute
#SBATCH --account=bd1231
#SBATCH --time=8:00:00
#SBATCH --cpus-per-task=1
#SBATCH --ntasks=20
#SBATCH --mem=0
#SBATCH --constraint=512G
#SBATCH --output=./slurm_out/slurm-%j.out
#SBATCH --error=./slurm_out/slurm-%j.err

# Begin of section with executable commands

python make_plots.py --day_start 1 --day_stop 9 &
python make_plots.py --day_start 9 --day_stop 17 &
python make_plots.py --day_start 17 --day_stop 25 &
python make_plots.py --day_start 25 --day_stop 33 &
python make_plots.py --day_start 33 --day_stop 41 &
python make_plots.py --day_start 41 --day_stop 49 &
python make_plots.py --day_start 49 --day_stop 57 &
python make_plots.py --day_start 57 --day_stop 65 &
python make_plots.py --day_start 65 --day_stop 73 &
python make_plots.py --day_start 73 --day_stop 81 &
python make_plots.py --day_start 81 --day_stop 89 &
python make_plots.py --day_start 89 --day_stop 97 &
python make_plots.py --day_start 97 --day_stop 105 &
python make_plots.py --day_start 105 --day_stop 113 &
python make_plots.py --day_start 113 --day_stop 121 &
python make_plots.py --day_start 121 --day_stop 129 &
python make_plots.py --day_start 129 --day_stop 137 &
python make_plots.py --day_start 137 --day_stop 145 &
python make_plots.py --day_start 145 --day_stop 153 &
python make_plots.py --day_start 153 --day_stop 161 &
wait
